"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
type Plan={code:string;name:string;monthlyPriceTHB:number|null;billingInterval:string;features:string[]};
const labels:Record<string,string>={"market.basic":"Market basics","market.realtime":"Realtime market","portfolio.basic":"Portfolio basics","portfolio.full":"Full portfolio","research.summary":"Research summaries","research.advanced":"Advanced research","risk.advanced":"Advanced risk","paper.trading":"Paper trading","formula.lab":"Formula Lab","backtest":"Backtesting","oos.holdout.walkforward":"OOS / Holdout / Walk-forward","enterprise.workspace":"Enterprise workspace","api":"API access","audit.export":"Audit export","governance":"Governance"};
const money=(n:number|null)=>n==null?"Custom":n===0?"Free":`฿${n.toLocaleString("en-US")}/mo`;
export default function LunaPricingPage(){
 const [plans,setPlans]=useState<Plan[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/luna2/plans").then(r=>r.json()).then(d=>setPlans(d.plans??[])).finally(()=>setLoading(false));},[]);
 return <main className="min-h-screen bg-[#f7f7f4] text-[#171817]"><section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-12">
 <div className="mb-12 flex items-center justify-between"><div><div className="text-xs font-semibold tracking-[0.28em] text-[#74766f]">LUNA</div><h1 className="mt-3 text-3xl font-medium tracking-tight sm:text-5xl">Investment intelligence, built as a system.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#66685f] sm:text-base">One platform for market intelligence, fundamentals, quantitative research, risk and paper trading.</p></div><a href="/luna" className="hidden rounded-full border border-[#d8d8d0] px-5 py-2.5 text-sm sm:block">Open Control Room</a></div>
 {loading?<div className="rounded-3xl border border-[#e2e2da] bg-white p-10 text-sm text-[#74766f]">Loading plans…</div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-5">{plans.map(plan=><article key={plan.code} className="flex min-h-[440px] flex-col rounded-3xl border border-[#deded6] bg-white p-6 shadow-[0_12px_40px_rgba(0,0,0,0.035)]"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[0.18em] text-[#777970]">{plan.code}</span>{plan.code==="PRO"&&<span className="rounded-full bg-[#171817] px-2.5 py-1 text-[10px] text-white">POPULAR</span>}</div><h2 className="mt-5 text-xl font-medium">{plan.name}</h2><div className="mt-3 text-2xl font-semibold">{money(plan.monthlyPriceTHB)}</div><div className="mt-1 text-xs text-[#888a82]">{plan.billingInterval==="custom"?"Tailored commercial terms":"Cancel or change plan from billing"}</div><div className="my-7 h-px bg-[#ecece6]"/><ul className="space-y-3 text-sm">{plan.features.map(f=><li key={f} className="flex gap-2.5"><Check size={16} className="mt-0.5 shrink-0 text-[#555850]"/><span>{labels[f]??f}</span></li>)}</ul><button disabled className="mt-auto flex w-full items-center justify-center gap-2 rounded-2xl border border-[#deded6] bg-[#f7f7f4] px-4 py-3 text-sm text-[#777970]">{plan.code==="ENTERPRISE"?"Contact sales":"Start with LUNA"}<ArrowRight size={15}/></button></article>)}</div>}
 <div className="mt-8 flex flex-col gap-3 rounded-3xl border border-[#deded6] bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0" size={19}/><div><div className="text-sm font-medium">Billing is isolated from trading execution.</div><div className="mt-1 text-xs leading-5 text-[#777970]">Current commercial layer is paper-only. No live-money execution is enabled by purchasing a plan.</div></div></div><span className="text-xs font-medium text-[#777970]">LIVE MONEY: LOCKED</span></div>
 </section></main>;
}